name: 'Bump and changelog using commitizen'
description: 'Create a commit bumping the version of your project and creating a changelog file'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'purple'
inputs:
  dry_run:
    description: 'Run without creating commit, output to stdout'
    default: "false"
    required: false
  prerelease:
    description: 'Set as prerelease version'
    default: "false"
    required: false
  changelog:
    description: 'Create changelog when bumping the version'
    default: "true"
    required: false
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
    default: 'master'
